### ISSUE TITLE
Pdk.__init__ (9.40.0) leaves __pydantic_extra__ uninitialised → copy.copy(pdk) raises AttributeError

### ISSUE THREAD

**Issue by thanojo** [gdsfactory/gdsfactory#4485]
**Describe the bug**

`copy.copy(pdk)` raises `AttributeError: 'Pdk' object has no attribute '__pydantic_extra__'` on any `Pdk` instance since gdsfactory 9.40.0.

9.40.0 introduced a custom `Pdk.__init__` (`gdsfactory/pdk.py`) that builds the model via `model_construct` and copies selected slots onto `self`: `__dict__`, `__pydantic_fields_set__`, `__pydantic_private__`. It does not copy `__pydantic_extra__`, which is a slot on `BaseModel`. Because `model_construct` ran on a throw-away instance, `self.__pydantic_extra__` remains an uninitialised slot.

When anything then calls `copy.copy(pdk)`, pydantic's `BaseModel.__copy__` does:

```python
_object_setattr(m, '__pydantic_extra__', copy(self.__pydantic_extra__))
```

The RHS access goes through `Pdk.__getattr__` → `super().__getattribute__('__pydantic_extra__')` → real `AttributeError`, which propagates.

This breaks any downstream code that copies a Pdk — e.g. server lifespans that snapshot the active PDK during hot reload. Downgrading to 9.39.x fixes it.

**To Reproduce**

```bash
uv init repro && cd repro
```

`pyproject.toml`:
```toml
[project]
name = "repro"
version = "0"
requires-python = "~=3.12.0"
dependencies = ["cspdk", "gdsfactory==9.40.0"]

[tool.uv]
# cspdk 1.4.2 still pins gdsfactory~=9.34.0; override to demo the regression
override-dependencies = ["gdsfactory==9.40.0"]
```

```bash
uv sync
uv run python -c "
from cspdk.si220.cband import PDK
import copy
copy.copy(PDK)
"
```

Result:
```
File ".../pydantic/main.py", line 960, in __copy__
    _object_setattr(m, '__pydantic_extra__', copy(self.__pydantic_extra__))
File ".../pydantic/main.py", line 1023, in __getattr__
    return super().__getattribute__(item)
AttributeError: 'Pdk' object has no attribute '__pydantic_extra__'. Did you mean: '__pydantic_fields__'?
```

Same traceback on any Pdk instance (`gf.get_active_pdk()`, a custom `Pdk(...)`, etc.).

**Expected behavior**

`copy.copy(pdk)` returns a shallow copy without raising, as it did in 9.39.x and earlier.

**Suggested fix**

One-line addition in `Pdk.__init__` (`gdsfactory/pdk.py`), alongside the existing `__pydantic_private__` copy:

```python
object.__setattr__(self, "__pydantic_extra__", constructed.__pydantic_extra__)
```

Verified locally by monkey-patching `Pdk.__init__` to include the line above — the same repro then runs cleanly.

A regression test covering `copy.copy(pdk)` on a `Pdk` instance would prevent recurrence.

**Environment (please complete the following information):**

- [x] I have reviewed the documentation, discussions and issues and found no relevant solution.
- [x] I understand that this is an open-source project, and maintainers may not have the resources to address every issue. I am prepared to contribute by fixing the issue myself or hiring someone to do so, if needed, and accept that the issue may not be resolved otherwise.
- [x] I am using the latest version of GDSFactory, with Python 3.11, 3.12, or 3.13.

```
3.12.12 (main, Feb 12 2026, 00:42:34) [Clang 21.1.4 ]

Modules
 python       3.12.12
 gdsfactory   9.40.0
 gplugins     2.0.1
 kfactory     2.4.6
 sax          0.16.14
 tidy3d       2.8.5
```

Regression bisected to #4465 (9.39.3 → 9.40.0 diff of `gdsfactory/pdk.py`), commit e48cde2, which added the custom `Pdk.__init__`.

cc @joamatab (author/merger of #4465), @sebastian-goeldi (requested reviewer) — flagging since the `Pdk.__init__` change in that PR was bundled with the shapes work and didn't get a dedicated review comment.
