### ISSUE TITLE
9.0.0 Hiccup: AttributeError: 'Cell' object has no attribute 'locked'

### ISSUE THREAD

**Issue by ghost** [gdsfactory/gdsfactory#3687]
**Describe the bug**
Using the [Dummy Fill / Tiling ](https://gdsfactory.github.io/gdsfactory/notebooks/04_components_geometry.html#dummy-fill-tiling) tutorial, throws the error: 

```python
AttributeError: 'Cell' object has no attribute 'locked'
```

**To Reproduce**

```python
import kfactory as kf
from kfactory.utils.fill import fill_tiled

import gdsfactory as gf

c = kf.DKCell("ToFill")
c.shapes(kf.kcl.layer(1, 0)).insert(
    kf.kdb.DPolygon.ellipse(kf.kdb.DBox(5000, 3000), 512)
)
c.shapes(kf.kcl.layer(10, 0)).insert(
    kf.kdb.DPolygon(
        [kf.kdb.DPoint(0, 0), kf.kdb.DPoint(5000, 0), kf.kdb.DPoint(5000, 3000)]
    )
)

fc = kf.DKCell()
fc.shapes(fc.kcl.layer(2, 0)).insert(kf.kdb.DBox(20, 40))
fc.shapes(fc.kcl.layer(3, 0)).insert(kf.kdb.DBox(30, 15))

fill_tiled(
    c,
    fc,
    [(kf.kdb.LayerInfo(1, 0), 0)],
    exclude_layers=[
        (kf.kdb.LayerInfo(10, 0), 100),
        (kf.kdb.LayerInfo(2, 0), 0),
        (kf.kdb.LayerInfo(3, 0), 0),
    ],
    x_space=5,
    y_space=5,
)

gdspath = "mzi_fill.gds"
c.write(gdspath)
c = gf.import_gds(gdspath, cellname="ToFill")
c.plot()
```

**Expected behavior**
Works in 8.32.2,

**Suggested fix**
Unsure

**Environment (please complete the following information):**

- [x] I have reviewed the documentation, discussions and issues and found no relevant solution.
- [x] I understand that this is an open-source project, and maintainers may not have the resources to address every issue. I am prepared to contribute by fixing the issue myself or hiring someone to do so, if needed, and accept that the issue may not be resolved otherwise.
- [x] I am using the latest version of GDSFactory, with Python 3.11, 3.12, or 3.13.

Please provide the output for the following code:

```python
3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]
venv\Scripts\python.exe
python 3.13.1
gdsfactory 9.0.0
```

**Comment by joamatab** [comment]
Hi, can you `pip install gdsfactory --upgrade`? we just released 9.0.1

**Comment by joamatab** [comment]
maybe in 2 or 3 min after this finishes :)

https://github.com/gdsfactory/gdsfactory/actions/runs/13442238496/job/37559257179

**Comment by sebastian-goeldi** [comment]
Argh. This is also a mistake in kfactory. It should pin klayout to >=0.29.1 as we are now using the locking mechanism. But we forgot to bump that requirement.
